In [1]:
import pandas as pd
import numpy as np

In [2]:
act_report=pd.read_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/Activity Report_v3.csv')
act_report.rename(columns={'textbox43':'Event'},inplace=True)
act_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19841 entries, 0 to 19840
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   GroupName         0 non-null      float64
 1   UnitName          19841 non-null  object 
 2   StartTime         19841 non-null  object 
 3   MovingTimeSecs    19841 non-null  object 
 4   MilesDriven       19568 non-null  object 
 5   MaxSpeed          19841 non-null  int64  
 6   StopTime          19841 non-null  object 
 7   Event             19841 non-null  object 
 8   StopLengthSecs    19841 non-null  object 
 9   ContactName       19841 non-null  object 
 10  textbox45         19841 non-null  object 
 11  textbox54         19841 non-null  int64  
 12  textbox28         19841 non-null  object 
 13  textbox29         19841 non-null  object 
 14  textbox30         19841 non-null  int64  
 15  textbox32         19841 non-null  object 
 16  MovingTimeSecs_1  19841 non-null  object

In [3]:
act_report['Event'].value_counts()

Event
Idle            17012
Parked/Idle      2009
Ign Off           812
Idle/Ign Off        8
Name: count, dtype: int64

In [4]:
geofences_report=pd.read_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/Geofences InOut Report.csv')
geofences_report.info()
geofences_report['GeofenceName'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   textbox12       249 non-null    object 
 1   UnitName        249 non-null    object 
 2   textbox18       0 non-null      float64
 3   EventTime       249 non-null    object 
 4   GeofenceName    249 non-null    object 
 5   GeofenceEvent1  249 non-null    object 
 6   Schedule        0 non-null      float64
dtypes: float64(2), object(5)
memory usage: 13.7+ KB


GeofenceName
Espera para cargue                                                                               187
LIRIOS : 91-38 Carrera 50  Medellín Antioquia 050004                                              13
HELICONIA                                                                                         11
ZEUSS Los Lagos                                                                                   11
ZEUSS Doña Maria                                                                                  10
Punto de cargue                                                                                    9
ZEUSS Las Vegas                                                                                    2
ZEUSS Doña Maria : Cl. 87 Sur #55-383 a 55-587, La Estrella, La Estrella, Antioquia, Colombia      1
PLANTA BENEFICIO PINTADA                                                                           1
HELICONIA : Kr50bb 90aa-40, La Estrella, Antioquia, Colombia                  

In [7]:
cu=pd.read_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/cu.csv',sep=';',encoding='latin1')
cu.info()
cu['Unit Type'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 48 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       22 non-null     int64  
 1   Owner                    22 non-null     object 
 2   Unit ID                  22 non-null     object 
 3   Unit                     22 non-null     object 
 4   Peripherals              0 non-null      float64
 5   BillingPeriod            22 non-null     object 
 6   Reporting Status         0 non-null      float64
 7   Show Until               0 non-null      float64
 8   Billing Group            1 non-null      object 
 9   Last Event Date          22 non-null     object 
 10  Monthly Fee              22 non-null     int64  
 11  Bill To                  0 non-null      float64
 12  Assigned To              22 non-null     object 
 13  Linked Mode              22 non-null     int64  
 14  Paired GPS               0 n

Unit Type
Queclink GV55W                                  13
GenX 5P                                          2
CalAmp 4232 - 3G - LMU4232H-RH00-G1000           2
GenX 651B                                        1
CalAmp 2630 - HSPA -LMU26H3001-G1000             1
CalAmp 0330H - 3G - LMU0330H-SKM6-G1000          1
Topfly PioneerX                                  1
CalAmp 2630 - GEMALTO HSPA -LMU26H3001-JAM01     1
Name: count, dtype: int64

In [10]:
calamp=cu[cu['Unit Type'].str.contains('CalAmp')]
calamp['IMEI'].to_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/calamp.csv')


In [32]:
calamp_06112025=pd.read_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/calamp_devices.csv')
calamp_06112025.info()
calamp_06112025_script_fir=calamp_06112025[['Model','IMEI','Script Identifier','Firmware Version','Last Event Time']]
calamp_06112025_script_fir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 64 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   ID                                    5 non-null      int64  
 1   Name                                  0 non-null      float64
 2   Identifier                            5 non-null      int64  
 3   Model                                 5 non-null      object 
 4   User ESN Mobile Id                    0 non-null      float64
 5   EOL                                   5 non-null      object 
 6   Enabled Services                      0 non-null      float64
 7   Asset                                 0 non-null      float64
 8   Account                               5 non-null      object 
 9   Status                                5 non-null      object 
 10  Last Event Time                       0 non-null      float64
 11  JPOD Firmware          

Model             IMEI  Script Identifier Firmware Version  \
0  LMU4232  357041068889230             55.168              85f   
1  LMU2630  352556102327058             55.161              85f   
2   LMU330  359369091108460              7.163              29b   
3  LMU2630  351628093163098             55.610              71a   
4  LMU4232  357041068850372             55.161              85f   

   Last Event Time  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN

Se cargó tarea a 359369091108460 y 351628093163098 para actualizar firmware.

In [11]:
queclink=cu[cu['Unit Type'].str.contains('Queclink')]
queclink['IMEI'].to_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/queclink.csv')

In [29]:
queclink_06112025=pd.read_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/queclink_devices.csv',sep=';')
queclink_06112025.info()
queclink_06112025_script_fir=queclink_06112025[['IMEI','Configuration Version','Firmware Version']]
queclink_06112025_script_fir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Device Name                     7 non-null      float64
 1   Last Report Date                13 non-null     object 
 2   Create Time                     12 non-null     object 
 3   IMEI                            13 non-null     int64  
 4   Device Type                     13 non-null     object 
 5   Group                           13 non-null     object 
 6   Iccid                           13 non-null     object 
 7   MCU Firmware Version            0 non-null      float64
 8   Modem Version                   0 non-null      float64
 9   Firmware Version                13 non-null     object 
 10  Configuration Version           13 non-null     int64  
 11  Hardware Version                13 non-null     float64
 12  Battery Percentage              13 non

IMEI  Configuration Version Firmware Version
0   868574042873666                    102        R00A13V02
1   868574042841283                    102        R00A13V02
2   868574042930656                    102        R00A12V03
3   868574042918529                    102        R00A12V03
4   868574042747357                    102        R00A12V03
5   868574042665898                    102        R00A12V03
6   868574042713987                    103        R00A12V03
7   868574042716956                    102        R00A12V03
8   868574042733506                    102        R00A12V03
9   868574042725965                    102        R00A12V03
10  868574042712609                    102        R00A12V03
11  868574042394986                    102        R00A12V03
12  868574042405311                    102        R00A12V03

Solo está disponible R00A12V03 en QMS.

In [12]:
genx=cu[cu['Unit Type'].str.contains('GenX')]
genx['IMEI'].to_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/genx.csv')

In [30]:
topfly=cu[cu['Unit Type'].str.contains('Topfly')]
topfly['IMEI'].to_csv('/home/jlhb1984/py-projects/data/Triturados y Arenas Antioquia TS000158008/topfly.csv')
#config=607, firmware=(V1.0.1.5)